#
# test.yml
# Run the tests
#

name: Test

on:
  push:

jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
        - '3.x'
        - '2.7'

    steps:

    - name: Check out the code
      uses: actions/checkout@v3

    - name: Select Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install --upgrade octoprint pytest

    - name: Run tests
      run: pytest
